
#define DANGER_MODE_KEY @"dangerMode"
#define IPHONE_TYPE_KEY @"iPhoneType"
#define MOBILE_TYPE_KEY @"mobileType"
#define HOME_TYPE_KEY @"homeType"
#define WORK_TYPE_KEY @"workType"
#define MAIN_TYPE_KEY @"mainType"
#define OTHER_TYPE_KEY @"otherType"
#define HOME_FAX_TYPE_KEY @"homeFaxType"
#define WORK_FAX_TYPE_KEY @"workFaxType"
#define OTHER_FAX_TYPE_KEY @"otherFaxType"
#define PAGER_TYPE_KEY @"pagerType"